[default]
index = greenhouse

[monitor:///var/log/greenhouse.log]
disabled   = false
index      = greenhouse
sourcetype = greenhouse:log

[monitor:///var/log/greenhouse/greenhouse_api.json]
disabled   = false
sourcetype = greenhouse:api:json
index      = greenhouse
